name: Hello World

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: |
          echo "hello world, chama"
      - name: Current Date
        run: date
      - name: List Directory Contents
        run: ls -a
